/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class GetelecInterface */

#ifndef _Included_GetelecInterface
#define _Included_GetelecInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     GetelecInterface
 * Method:    Getelec_new_with_config
 * Signature: (Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_GetelecInterface_Getelec_1new_1with_1config
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     GetelecInterface
 * Method:    Getelec_delete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_GetelecInterface_Getelec_1delete
  (JNIEnv *, jobject, jlong);

/*
 * Class:     GetelecInterface
 * Method:    Getelec_setRadius
 * Signature: (J[D)V
 */
JNIEXPORT void JNICALL Java_GetelecInterface_Getelec_1setRadius
  (JNIEnv *, jobject, jlong, jdoubleArray);

/*
 * Class:     GetelecInterface
 * Method:    Getelec_setField
 * Signature: (J[D)V
 */
JNIEXPORT void JNICALL Java_GetelecInterface_Getelec_1setField
  (JNIEnv *, jobject, jlong, jdoubleArray);

/*
 * Class:     GetelecInterface
 * Method:    Getelec_setGamma
 * Signature: (J[D)V
 */
JNIEXPORT void JNICALL Java_GetelecInterface_Getelec_1setGamma
  (JNIEnv *, jobject, jlong, jdoubleArray);

/*
 * Class:     GetelecInterface
 * Method:    Getelec_setkT
 * Signature: (J[D)V
 */
JNIEXPORT void JNICALL Java_GetelecInterface_Getelec_1setkT
  (JNIEnv *, jobject, jlong, jdoubleArray);

/*
 * Class:     GetelecInterface
 * Method:    Getelec_setWorkFunction
 * Signature: (J[D)V
 */
JNIEXPORT void JNICALL Java_GetelecInterface_Getelec_1setWorkFunction
  (JNIEnv *, jobject, jlong, jdoubleArray);

/*
 * Class:     GetelecInterface
 * Method:    Getelec_setBandDepth
 * Signature: (J[D)V
 */
JNIEXPORT void JNICALL Java_GetelecInterface_Getelec_1setBandDepth
  (JNIEnv *, jobject, jlong, jdoubleArray);

/*
 * Class:     GetelecInterface
 * Method:    Getelec_setEffectiveMass
 * Signature: (J[D)V
 */
JNIEXPORT void JNICALL Java_GetelecInterface_Getelec_1setEffectiveMass
  (JNIEnv *, jobject, jlong, jdoubleArray);

/*
 * Class:     GetelecInterface
 * Method:    Getelec_run
 * Signature: (JZ)I
 */
JNIEXPORT jint JNICALL Java_GetelecInterface_Getelec_1run
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     GetelecInterface
 * Method:    Getelec_getCurrentDensities
 * Signature: (J)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_GetelecInterface_Getelec_1getCurrentDensities
  (JNIEnv *, jobject, jlong);

/*
 * Class:     GetelecInterface
 * Method:    Getelec_getNottinghamHeats
 * Signature: (J)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_GetelecInterface_Getelec_1getNottinghamHeats
  (JNIEnv *, jobject, jlong);

/*
 * Class:     GetelecInterface
 * Method:    Getelec_calculateTransmissionForEnergy
 * Signature: (JDI)D
 */
JNIEXPORT jdouble JNICALL Java_GetelecInterface_Getelec_1calculateTransmissionForEnergy
  (JNIEnv *, jobject, jlong, jdouble, jint);

/*
 * Class:     GetelecInterface
 * Method:    Getelec_calculateTransmissionForEnergies
 * Signature: (J[DI)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_GetelecInterface_Getelec_1calculateTransmissionForEnergies
  (JNIEnv *, jobject, jlong, jdoubleArray, jint);

/*
 * Class:     GetelecInterface
 * Method:    Getelec_calculateTransmissionForManyEnergies
 * Signature: (J[DI)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_GetelecInterface_Getelec_1calculateTransmissionForManyEnergies
  (JNIEnv *, jobject, jlong, jdoubleArray, jint);

/*
 * Class:     GetelecInterface
 * Method:    Getelec_getSpectraEnergies
 * Signature: (JI)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_GetelecInterface_Getelec_1getSpectraEnergies
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     GetelecInterface
 * Method:    Getelec_getSpectraValues
 * Signature: (JI)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_GetelecInterface_Getelec_1getSpectraValues
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     GetelecInterface
 * Method:    Getelec_getSpectraDerivatives
 * Signature: (JI)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_GetelecInterface_Getelec_1getSpectraDerivatives
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     GetelecInterface
 * Method:    Getelec_getBarrierValues
 * Signature: (J[D[DI)V
 */
JNIEXPORT void JNICALL Java_GetelecInterface_Getelec_1getBarrierValues
  (JNIEnv *, jobject, jlong, jdoubleArray, jdoubleArray, jint);

/*
 * Class:     GetelecInterface
 * Method:    Getelec_getBarrierIntegrationLimits
 * Signature: (J[D[DI)V
 */
JNIEXPORT void JNICALL Java_GetelecInterface_Getelec_1getBarrierIntegrationLimits
  (JNIEnv *, jobject, jlong, jdoubleArray, jdoubleArray, jint);

#ifdef __cplusplus
}
#endif
#endif
